<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
    <!ELEMENT students (student+)>
    <!ELEMENT student (name, dob, major)>
    <!ATTLIST student id ID #REQUIRED>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT dob (#PCDATA)>
    <!ELEMENT major (#PCDATA)>
]>
<students>
    <student id="SV001">
        <name>Nguyễn Văn A</name>
        <dob>2001-05-10</dob>
        <major>Công nghệ thông tin</major>
    </student>
    <student id="SV002">
        <name>Trần Thị B</name>
        <dob>2002-08-21</dob>
        <major>Quản trị kinh doanh</major>
    </student>
    <student id="SV003">
        <name>Lê Văn C</name>
        <dob>2001-11-30</dob>
        <major>Kế toán</major>
    </student>
</students>
