<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hospital [
    <!ELEMENT hospital (appointment+)>

    <!ELEMENT appointment (patient, doctor)>
    <!ATTLIST appointment
        mã ID #REQUIRED
        ngày CDATA #REQUIRED
        trạng_thái CDATA #REQUIRED
    >

    <!ELEMENT patient (name, dob)>
    <!ATTLIST patient
        mã_bn ID #REQUIRED
    >
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT dob (#PCDATA)>

    <!ELEMENT doctor (name, specialty)>
    <!ATTLIST doctor
        mã_bs ID #REQUIRED
    >
    <!ELEMENT specialty (#PCDATA)>
]>

<hospital>
    <appointment mã="A001" ngày="2025-03-05" trạng_thái="Đã khám">
        <patient mã_bn="P001">
            <name>vũ đình sang</name>
            <dob>1990-07-15</dob>
        </patient>
        <doctor mã_bs="D001">
            <name>lê văn mộng</name>
            <specialty>Nội khoa</specialty>
        </doctor>
    </appointment>

    <appointment mã="A002" ngày="2025-03-10" trạng_thái="Chưa khám">
        <patient mã_bn="P002">
            <name>lê văn dinh</name>
            <dob>1985-12-20</dob>
        </patient>
        <doctor mã_bs="D002">
            <name>Nguyễn Văn Dee</name>
            <specialty>Ngoại khoa</specialty>
        </doctor>
    </appointment>
</hospital>
