<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE orders [
    <!ELEMENT orders (order+)>

    <!-- order -->
    <!ELEMENT order (item+)>
    <!ATTLIST order
        id ID #REQUIRED
        customer CDATA #REQUIRED
        date CDATA #REQUIRED
    >

    <!-- product item -->
    <!ELEMENT item (name)>
    <!ATTLIST item
        id ID #REQUIRED
        quantity CDATA #REQUIRED
        price CDATA #REQUIRED
    >
    <!ELEMENT name (#PCDATA)>
]>

<orders>

    <!-- Đơn hàng 1 -->
    <order id="O001" customer="Nguyễn Văn A" date="2025-03-02">
    <item id="P001" quantity="2" price="500">
        <name>Điện thoại Samsung</name>
    </item>
    <item id="P002" quantity="1" price="1000">
        <name>Laptop Dell</name>
    </item>
</order>

<order id="O002" customer="Trần Thị B" date="2025-03-10">
    <item id="P003" quantity="3" price="20">
        <name>Bút bi Thiên Long</name>
    </item>
    <item id="P004" quantity="5" price="10">
        <name>Tập học sinh</name>
    </item>
</order>


</orders>
